config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about' => 'pages#about'
  resource :users
  get 'signup' => 'users#new'
  get 'thanks' => 'pages#thanks'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'content' => 'pages#content'
  get 'logout' => 'sessions#destroy'
  get 'message' => 'pages#message'
  post 'message' => 'pages#message'

  get 'check_signature_display' => 'webhook#check_signature_display'
  post 'check_signature' => 'webhook#check_signature'
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :require_user, only: [:content, :about, :message]


	def home
	end
	def about
		intercom = Intercom::Client.new(token: "dG9rOjY5NzZkNDJkXzdhNzZfNDdmNl85OWQ5X2IzZTk1ZjJiNmM0MjoxOjA=")
  		intercom.events.create(event_name: "Click About", created_at: Time.now.to_i, user_id: current_user.id)

	end
	def thanks
	end
	def content

		intercom = Intercom::Client.new(token: "dG9rOjY5NzZkNDJkXzdhNzZfNDdmNl85OWQ5X2IzZTk1ZjJiNmM0MjoxOjA=")
  		count = intercom.counts.for_type(type: 'user', count: 'segment')
  		@new_user_count = count.user["segment"][3]["New"]
			intercom_custom_data.user[:rails_controller_attr] = "Test Rails Controller"

	end
	def message
		intercom = Intercom::Client.new(token: "dG9rOjY5NzZkNDJkXzdhNzZfNDdmNl85OWQ5X2IzZTk1ZjJiNmM0MjoxOjA=")
		@usermessage = Message.new

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end
	def create
  		@user = User.find_by_email(params[:session][:email])
  		if @user && @user.authenticate(params[:session][:password])
    		session[:user_id] = @user.id
    		intercom = Intercom::Client.new(token: "dG9rOjY5NzZkNDJkXzdhNzZfNDdmNl85OWQ5X2IzZTk1ZjJiNmM0MjoxOjA=")
  			intercom.events.create(event_name: "Logged In", created_at: Time.now.to_i, user_id: @user.id)
    		redirect_to '/content'
        # intercomuser = intercom.users.find(:email => @user.email)
        # intercom.messages.create({
        #   :message_type => 'inapp',
        #   :body => "What's up #{intercomuser.last_seen_ip} :) ",
        #   :from => {
        #     :type => 'admin',
        #     :id   => "125999"
        #   },
        #   :to => {
        #     :type => "user",
        #     :email   => @user.email
        #   }
        # })

  		else
    		redirect_to '/login'
  		end
	end
  	def destroy
    	session[:user_id] = nil
    	redirect_to '/'
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create
	    @user = User.new(user_params)
	    if @user.save
	    	session[:user_id] = @user.id
	      	redirect_to '/content'
	    else
	      	redirect_to '/signup'
	    end
	end
	private
	def user_params
	    params.require(:user).permit(:fullname, :email, :password)
	end
end

app/controllers/webhook_controller.rb
class WebhookController < ApplicationController
  # before_filter :init_check_signature
  skip_before_filter  :verify_authenticity_token
  # respond_to :json
  require 'json'

  def check_signature
    # cache_signatures = ActiveSupport::Cache::MemoryStore.new
    # cache_signatures.write('test','success')
    json_data = request.body.read
    # binding.pry
    # @request = Rails.cache.read('post_request')
    if json_data != ""
      Rails.cache.write('post_request',json_data)
      secret = "kevinsecretshhhhh"
      digest = OpenSSL::Digest.new('sha1')
      calculated_signature = OpenSSL::HMAC.hexdigest(digest, secret, json_data).prepend('sha1=')
      intercom_signature = request.env["HTTP_X_HUB_SIGNATURE"]
      # calculated_signature = "1234"
      # intercom_signature = "abcd"
      Rails.cache.write('calculated_signature',calculated_signature)
      Rails.cache.write('intercom_signature',intercom_signature)
      @calculated_signature = calculated_signature
      @intercom_signature = intercom_signature

      # send response back to Intercom
      render json: { text: "Got it!", status: 200}

      # process conversation note and create user note
      parsed_json = JSON.parse(json_data)
      webhook_topic = parsed_json["topic"]
      Rails.cache.write('webhook_topic', webhook_topic)
      item = parsed_json["data"]["item"]
      intercom = Intercom::Client.new(token:
      "dG9rOjY5NzZkNDJkXzdhNzZfNDdmNl85OWQ5X2IzZTk1ZjJiNmM0MjoxOjA=")

      # # check if topic is conversation.admin.noted
      if webhook_topic == "conversation.admin.noted"
        if item["conversation_parts"]["conversation_parts"][0]["body"] == "<p>webhook note</p>"
          time = Time.now
          userId = item["user"]["user_id"]
          note = intercom.notes.create(:body => "Note from Webhook, current timestamp: #{time}", :user_id => userId)
        end
      elsif webhook_topic == "conversation.user.created"
        convo_id = item["id"]
        if item["conversation_message"]["body"] == "<p>show bot</p>"
          userId = item["user"]["user_id"]
          reply = intercom.conversations.reply(:id => convo_id, :type => "admin", :admin_id => "125999", :message_type => "comment", :body => "This isn't Kevin. It's a bot!")
        end
      end

    end
    # else
    #   # binding.pry
    #   if Rails.cache.read('calculated_signature') != nil
    #     @calculated_signature = Rails.cache.read('calculated_signature')
    #     @intercom_signature = Rails.cache.read('intercom_signature')
    #   else
    #     @calculated_signature = "Nothing"
    #     @intercom_signature = "Received"
    #   end
    # end
    # # binding.pry
    # if @calculated_signature == @intercom_signature
    #   @success = "Woohoo!"
    # else
    #   @success = "Not the same!"
    # end
  end

  def check_signature_display
    # Get the cached request body
    @request = Rails.cache.read('post_request')
    @request = "No Request" if @request == ""

    # Check if there's a cached value for the signatures
    if Rails.cache.read('calculated_signature') != nil
      @calculated_signature = Rails.cache.read('calculated_signature')
      @intercom_signature = Rails.cache.read('intercom_signature')
      @topic = Rails.cache.read('webhook_topic')
    else
      @calculated_signature = "Nothing"
      @intercom_signature = "Received"
    end

    # Check if the signatures match
    if @calculated_signature == @intercom_signature
      @success = "Woohoo!"
    else
      @success = "Not the same!"
    end
  end
  # def init_check_signature
  #   cache_signatures = ActiveSupport::Cache::MemoryStore.new
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webhook_helper.rb
module WebhookHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
</head>

<%# Menu %>


<body>
	<div id="menu">
        <ul>
            <li><%= link_to "Home", '/' %></li>
            <li><%= link_to "About", '/about' %></li>
            <li><%= link_to "Sign Up", '/signup' %></li>
        </ul>
	</div>
	<div class="nav pull-right">
		<% if current_user %>
	  		<ul>
	    		<li><%= current_user.email %></li>
	    		<li><%= link_to "Log out", logout_path, method: "DELETE" %></li>
          <li><%= link_to "Webhook Checker", 'check_signature_display' %></a></li>
	  		</ul>
		<% else %>
	  		<ul>
	    		<li><%= link_to "Login", 'login' %></a></li>
	    		<li><%= link_to "Signup", 'signup' %></a></li>
          <li><%= link_to "Webhook Checker", 'check_signature_display' %></a></li>
	  		</ul>
		<% end %>

	</div>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>



	<%# Footer %>
	<div class="footer">
		<p>A KevintheChang Project</p>
	</div>

</body>

</html>

app/views/pages/about.html.erb
<%# Main section %>
<div class="main">
	<h1>About this project</h1>
</div>

<%# Supporting section %>
<div class="supporting">
	<h2>Join and share in the experiences</h2>
	<p>Stories automatically creates a digital journal filled with only your best photos.</p>
	<%= link_to "Sign Up", '/signup' %>
</div>

app/views/pages/content.html.erb
<h1>You are logged in to see this</h1>
<h2>There are <%= @new_user_count %> new users.</h2>

app/views/pages/home.html.erb
<%# Main section %>
<div class="main">
	<h1>Create and Share Stories</h1>
	<p><%= link_to "Learn More", 'about' %></p>
</div>

<%# Supporting section %>
<div class="supporting">
	<h2>Relive and share your adventures</h2>
	<p>Stories automatically creates a digital journal filled with only your best photos.</p>
</div>

<%# Secondary section %>
<div class="secondary">
	<img src="<%= asset_path('Nature-sea-scenery.jpg') %>" />
</div>

<%# Discover section %>
<div class="discover">
	<h2>Discover Stories from Other People</h2>
	<%= link_to "Learn More", 'about' %>
</div>

app/views/pages/message.html.erb
<%= form_for(@usermessage, :url message_path) do |f| %>
    	<div class="field">
			<%= f.text_area :subject, :placeholder => "Message Subject" %>
			<%= f.text_area :message, :placeholder => "Message" %>
    	</div>
    	<div class="actions">
        <%= f.submit "Sign Up", class: "btn-submit" %>
    	</div>
    <% end %>

app/views/pages/thanks.html.erb
<h1>Thanks man!</h1>

app/views/users/new.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg">
    <h1>Sign Up</h1>
  </div>
</div>

<div class="create">
  <div class="container">

    <!-- Your code here -->
    <%= form_for(@user) do |f| %>
    	<div class="field">
			<%= f.text_area :fullname, :placeholder => "Full Name" %>
			<%= f.text_area :email, :placeholder => "Email" %>
			<%= f.password_field :password, :placeholder => "Password" %>
    	</div>
    	<div class="actions">
        <%= f.submit "Sign Up", class: "btn-submit" %>
    	</div>
    <% end %>
  </div>
</div>

app/views/webhook/check_signature.html.erb
<p>Calculated Signature: <%= @calculated_signature %></p>
<p>Intercom's Signature: <%= @intercom_signature %></p>

<p id="result"><%= @success %></p>
<p><%= @request %></p>

app/views/webhook/check_signature_display.html.erb
<p>Calculated Signature: <%= @calculated_signature %></p>
<p>Intercom's Signature: <%= @intercom_signature %></p>
<p>Topic: <%= @topic %></p>

<p id="result"><%= @success %></p>
<p><%= @request %></p>